<link rel="stylesheet" href="${request.contextPath}/static/markdown/css/editormd.css" />
<script type="text/javascript" charset="utf-8" src="${request.contextPath}/static/markdown/lib/marked.min.js"></script>
<script type="text/javascript" charset="utf-8" src="${request.contextPath}/static/markdown/lib/prettify.min.js"></script>
<script type="text/javascript" charset="utf-8" src="${request.contextPath}/static/markdown/lib/raphael.min.js"></script>
<script type="text/javascript" charset="utf-8" src="${request.contextPath}/static/markdown/lib/underscore.min.js"></script>
<script type="text/javascript" charset="utf-8" src="${request.contextPath}/static/markdown/lib/sequence-diagram.min.js"></script>
<script type="text/javascript" charset="utf-8" src="${request.contextPath}/static/markdown/lib/flowchart.min.js"></script>
<script type="text/javascript" charset="utf-8" src="${request.contextPath}/static/markdown/lib/jquery.flowchart.min.js"></script>
<script type="text/javascript" charset="utf-8" src="${request.contextPath}/static/markdown/editormd.min.js"></script>